services:
  portfolio:
    build:
      context: .
      dockerfile: docker/application.Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - 4440:4440
      - 4441:4441
      - 4442:4442
    environment:
      NODE_ENV: development

  postgres:
    build:
      context: .
      dockerfile: docker/database.Dockerfile
